# Custom Chatbot Project

TODO: In this cell, write an explanation of which dataset you have chosen and why it is appropriate for this task

In [1]:
import os
import pandas as pd

os.listdir('./data/')

['2023_fashion_trends.csv',
 'nyc_food_scrap_drop_off_sites.csv',
 'character_descriptions.csv',
 '.ipynb_checkpoints']

In [2]:
data = pd.read_csv('./data/2023_fashion_trends.csv', index_col=0)

print(data.keys())
print(data.iloc[0].Trends)
print(data.iloc[0].Source)

data.sample(1)

Index(['Trends', 'Source'], dtype='object')
2023 Fashion Trend: Red. Glossy red hues took over the Fall 2023 runways ranging from Sandy Liang and PatBo to Tory Burch and Wiederhoeft. Think: Juicy reds with vibrant orange undertones that would look just as good in head-to-toe looks (see: a pantsuit) as accent accessory pieces (shoes, handbags, jewelry).
7 Fashion Trends That Will Take Over 2023 — Shop Them Now

,Trends,Source
URL,,
https://www.refinery29.com/en-us/fashion-trends-2023,2023 Fashion Trend: Red. Glossy red hues took ...,7 Fashion Trends That Will Take Over 2023 — Sh...

In [3]:
# Not ideal to use this dataset
data = pd.read_csv('./data/nyc_food_scrap_drop_off_sites.csv', index_col=0)

print(data.keys())

data.sample(1)

Index(['borough', 'ntaname', 'food_scrap_drop_off_site', 'location',
       'hosted_by', 'open_months', 'operation_day_hours', 'website', 'borocd',
       'councildist', 'latitude', 'longitude', 'precinct', 'object_id',
       'location_point', ':@computed_region_yeji_bk3q',
       ':@computed_region_92fq_4b7q', ':@computed_region_sbqj_enih',
       ':@computed_region_efsh_h5xi', ':@computed_region_f5dn_yrer', 'notes',
       'ct2010', 'bbl', 'bin'],
      dtype='object')

,borough,ntaname,food_scrap_drop_off_site,location,hosted_by,open_months,operation_day_hours,website,borocd,councildist,...,location_point,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,notes,ct2010,bbl,bin
12,Brooklyn,Crown Heights (North),Walt L Shamel Community Garden,"1097 Dean St, Brooklyn, NY 11216",Volunteers at Walt L Shamel Community Garden,End of March - January 30,Saturdays and Sundays (Start Time: 12:00 PM - ...,https://www.facebook.com/WaltLShamelCommunityG...,308,35,...,"{'type': 'Point', 'coordinates': [-73.953657, ...",2.0,48.0,49.0,17618.0,16.0,"Not accepted: meat, bones, or dairy",NaN,NaN,NaN

In [4]:
# Has description but not the best to use
data = pd.read_csv('./data/character_descriptions.csv')

print(data.keys())
print(data.iloc[0].Name)
print(data.iloc[0].Description)
print(data.iloc[0].Medium)
print(data.iloc[0].Setting)

data.head(1)

Index(['Name', 'Description', 'Medium', 'Setting'], dtype='object')
Emily
A young woman in her early 20s, Emily is an aspiring actress and Alice's daughter. She has a bubbly personality and a quick wit, but struggles with self-doubt and insecurity. She's also in a relationship with George.
Play
England

    Name                                        Description Medium  Setting
0  Emily  A young woman in her early 20s, Emily is an as...   Play  England

First, at the start of the notebook, you will write a short paragraph describing your dataset choice and setting up the scenario of when this customization would be useful.

This notebook will be using the dataset inside the `2023_fashion_trends.csv` file as it is describing fashion trends in 2023. It is ideal to use this dataset in a senario where an LLM is needed to answer questions about a specific year's fashion trend (in this context, 2023). Other datasets might not be useful or best to tailor for such a QnA chatbot task, where the data is not very descriptive or informative.

## Data Wrangling

TODO: In the cells below, load your chosen dataset into a `pandas` dataframe with a column named `"text"`. This column should contain all of your text data, separated into at least 20 rows.

In [5]:
data = pd.read_csv('./data/2023_fashion_trends.csv')

data

,URL,Trends,Source
0,https://www.refinery29.com/en-us/fashion-trend...,2023 Fashion Trend: Red. Glossy red hues took ...,7 Fashion Trends That Will Take Over 2023 — Sh...
1,https://www.refinery29.com/en-us/fashion-trend...,2023 Fashion Trend: Cargo Pants. Utilitarian w...,7 Fashion Trends That Will Take Over 2023 — Sh...
2,https://www.refinery29.com/en-us/fashion-trend...,"2023 Fashion Trend: Sheer Clothing. ""Bare it a...",7 Fashion Trends That Will Take Over 2023 — Sh...
3,https://www.refinery29.com/en-us/fashion-trend...,2023 Fashion Trend: Denim Reimagined. From dou...,7 Fashion Trends That Will Take Over 2023 — Sh...
4,https://www.refinery29.com/en-us/fashion-trend...,2023 Fashion Trend: Shine For The Daytime. The...,7 Fashion Trends That Will Take Over 2023 — Sh...
...,...,...,...
77,https://www.whowhatwear.com/spring-summer-2023...,"If lime green isn't your vibe, rest assured th...",Spring/Summer 2023 Fashion Trends: 21 Expert-A...
78,https://www.whowhatwear.com/spring-summer-2023...,"""As someone who can clearly (not fondly) remem...",Spring/Summer 2023 Fashion Trends: 21 Expert-A...
79,https://www.whowhatwear.com/spring-summer-2023...,"""Combine this design shift with the fact that ...",Spring/Summer 2023 Fashion Trends: 21 Expert-A...
80,https://www.whowhatwear.com/spring-summer-2023...,Thought party season ended at the stroke of mi...,Spring/Summer 2023 Fashion Trends: 21 Expert-A...
81,https://www.whowhatwear.com/spring-summer-2023...,"""This season, we saw the revival of the bubble...",Spring/Summer 2023 Fashion Trends: 21 Expert-A...

Are there any unique information in the `source` and `URL` columns? Are they repetative?

In [6]:
import numpy as np

print("Unique sources: ", len(np.unique(data['Source'].tolist())))
print("Unique URLs: ", len(np.unique(data['URL'].tolist())))

Unique sources:  5
Unique URLs:  5

The information in the sources and URLs are very repetative, we can just neglect them unless we need the model to be able to refrenece the answers. For simplicity, we will neglect both coulumns, and only use the `Trends` column.

In [7]:
data.drop(['URL', 'Source'], axis = 1, inplace = True)
data.head()

                                              Trends
0  2023 Fashion Trend: Red. Glossy red hues took ...
1  2023 Fashion Trend: Cargo Pants. Utilitarian w...
2  2023 Fashion Trend: Sheer Clothing. "Bare it a...
3  2023 Fashion Trend: Denim Reimagined. From dou...
4  2023 Fashion Trend: Shine For The Daytime. The...

Let's rename the `Trends` column to `text` as required by the task.

In [8]:
data.rename(columns={'Trends': 'text'}, inplace=True, errors='raise')
data

                                                 text
0   2023 Fashion Trend: Red. Glossy red hues took ...
1   2023 Fashion Trend: Cargo Pants. Utilitarian w...
2   2023 Fashion Trend: Sheer Clothing. "Bare it a...
3   2023 Fashion Trend: Denim Reimagined. From dou...
4   2023 Fashion Trend: Shine For The Daytime. The...
..                                                ...
77  If lime green isn't your vibe, rest assured th...
78  "As someone who can clearly (not fondly) remem...
79  "Combine this design shift with the fact that ...
80  Thought party season ended at the stroke of mi...
81  "This season, we saw the revival of the bubble...

[82 rows x 1 columns]

In [9]:
# just for simplicity, we rename it to df
df = data

## Custom Query Completion

TODO: In the cells below, compose a custom query using your chosen dataset and retrieve results from an OpenAI `Completion` model. You may copy and paste any useful code from the course materials.

First, let's encode all of the text into embeddings.

In [10]:
import openai
openai.api_base = "https://openai.vocareum.com/v1"
openai.api_key = "YOUR API KEY"

In [11]:
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
batch_size = 10
embeddings = []
for i in range(0, len(df), batch_size):
    # Send text data to OpenAI model to get embeddings
    response = openai.Embedding.create(
        input=df.iloc[i:i+batch_size]["text"].tolist(),
        engine=EMBEDDING_MODEL_NAME
    )
    
    # Add embeddings to list
    embeddings.extend([data["embedding"] for data in response["data"]])

# Add embeddings list to dataframe
df["embeddings"] = embeddings
df

,text,embeddings
0,2023 Fashion Trend: Red. Glossy red hues took ...,"[-0.02085592783987522, -0.02201749198138714, 0..."
1,2023 Fashion Trend: Cargo Pants. Utilitarian w...,"[-0.0017685757484287024, -0.02890433557331562,..."
2,"2023 Fashion Trend: Sheer Clothing. ""Bare it a...","[-0.010457162745296955, -0.019242258742451668,..."
3,2023 Fashion Trend: Denim Reimagined. From dou...,"[-0.015490234829485416, -0.005457699298858643,..."
4,2023 Fashion Trend: Shine For The Daytime. The...,"[-0.004975747317075729, 0.0017561460845172405,..."
...,...,...
77,"If lime green isn't your vibe, rest assured th...","[-0.0029100796673446894, -0.018196824938058853..."
78,"""As someone who can clearly (not fondly) remem...","[-0.01477336697280407, -0.00650231447070837, 0..."
79,"""Combine this design shift with the fact that ...","[-0.020839447155594826, -0.025072040036320686,..."
80,Thought party season ended at the stroke of mi...,"[-0.019966259598731995, -0.02226800099015236, ..."
81,"""This season, we saw the revival of the bubble...","[-0.031058592721819878, 0.0024474775418639183,..."

We will reuse several functions provided by the previous materials.

In [12]:
from openai.embeddings_utils import get_embedding, distances_from_embeddings

def get_rows_sorted_by_relevance(question, df):
    """
    Function that takes in a question string and a dataframe containing
    rows of text and associated embeddings, and returns that dataframe
    sorted from least to most relevant for that question
    """
    
    # Get embeddings for the question text
    question_embeddings = get_embedding(question, engine=EMBEDDING_MODEL_NAME)
    
    # Make a copy of the dataframe and add a "distances" column containing
    # the cosine distances between each row's embeddings and the
    # embeddings of the question
    df_copy = df.copy()
    df_copy["distances"] = distances_from_embeddings(
        question_embeddings,
        df_copy["embeddings"].values,
        distance_metric="cosine"
    )
    
    # Sort the copied dataframe by the distances and return it
    # (shorter distance = more relevant so we sort in ascending order)
    df_copy.sort_values("distances", ascending=True, inplace=True)
    return df_copy

In [24]:
# lets test it!
get_rows_sorted_by_relevance("What was the most popular fashion trends in 2023?", df)

,text,embeddings,distances
2,"2023 Fashion Trend: Sheer Clothing. ""Bare it a...","[-0.010457162745296955, -0.019242258742451668,...",0.126754
0,2023 Fashion Trend: Red. Glossy red hues took ...,"[-0.02085592783987522, -0.02201749198138714, 0...",0.128048
6,2023 Fashion Trend: Cobalt Blue. The strongest...,"[-0.007023967802524567, -0.021408261731266975,...",0.130673
63,"""Every season, there is a trend that speaks to...","[-0.010807233862578869, -0.018712835386395454,...",0.134043
44,I get it. Some of the trends on this list migh...,"[-0.021651821210980415, -0.00865799281746149, ...",0.134608
...,...,...,...
60,It seems this season is upping the ante when i...,"[0.029917040839791298, 0.013639058917760849, -...",0.220391
34,Sheer Layering. I never in my life thought I w...,"[-0.013640816323459148, -0.010081478394567966,...",0.224260
37,The-Bigger-the-Better Bags. Gone are the days ...,"[-0.01134550292044878, -0.003607184626162052, ...",0.227957
78,"""As someone who can clearly (not fondly) remem...","[-0.01477336697280407, -0.00650231447070837, 0...",0.230565
18,"Oversized Bags. As cute as they can be, tiny b...","[-0.0017445659032091498, -0.006407314911484718...",0.232099

Building custom query for the model.

In [16]:
import tiktoken

def create_prompt(question, df, max_token_count):
    """
    Given a question and a dataframe containing rows of text and their
    embeddings, return a text prompt to send to a Completion model
    """
    # Create a tokenizer that is designed to align with our embeddings
    tokenizer = tiktoken.get_encoding("cl100k_base")
    
    # Count the number of tokens in the prompt template and question
    prompt_template = """
Answer the question based on the context below, and if the question
can't be answered based on the context, say "I don't know"

Context: 

{}

---

Question: {}
Answer:"""
    
    current_token_count = len(tokenizer.encode(prompt_template)) + \
                            len(tokenizer.encode(question))
    
    context = []
    for text in get_rows_sorted_by_relevance(question, df)["text"].values:
        
        # Increase the counter based on the number of tokens in this row
        text_token_count = len(tokenizer.encode(text))
        current_token_count += text_token_count
        
        # Add the row of text to the list if we haven't exceeded the max
        if current_token_count <= max_token_count:
            context.append(text)
        else:
            break

    return prompt_template.format("\n\n###\n\n".join(context), question)

In [23]:
# testing the prompting

print(create_prompt("What was the most popular fashion trends in 2023?", df, max_token_count=400))

Answer the question based on the context below, and if the question
can't be answered based on the context, say "I don't know"

Context:

2023 Fashion Trend: Sheer Clothing. "Bare it all" has been the motto since the end of the lockdown. In 2023,  naked dressing makes its way from the red carpet – where celebrities like Cher and Rihanna have been sporting the trend forever – to street style. From a cellophane-like dress, worn over a boldly hued maxi skirt at Tory Burch's spring 2023 show, to a frothy frock revealing undergarments at Victoria Beckham, the previously risqué trend is coming not only for your weekend wardrobe but even workwear.

###

2023 Fashion Trend: Red. Glossy red hues took over the Fall 2023 runways ranging from Sandy Liang and PatBo to Tory Burch and Wiederhoeft. Think: Juicy reds with vibrant orange undertones that would look just as good in head-to-toe looks (see: a pantsuit) as accent accessory pieces (shoes, handbags, jewelry).

###

2023 Fashion Trend: Cobalt Blue. The strongest color story to come out of Spring 2023 runways, cobalt blue has burst through the collections with the freshness of a sea mist on a morning day. Just bright enough to warrant a double take, yet subtle enough to be worked into daily wear, it's the type of deep blue that will excite even the most color-averse. Bonus points: It pairs well with Pantone's Viva Magenta.

---

Question: What was the most popular fashion trends in 2023?
Answer:

Question and answering helper function.

In [22]:
COMPLETION_MODEL_NAME = "gpt-3.5-turbo-instruct"

def answer_question(
    question, df, max_prompt_tokens=1800, max_answer_tokens=150
):
    """
    Given a question, a dataframe containing rows of text, and a maximum
    number of desired tokens in the prompt and response, return the
    answer to the question according to an OpenAI Completion model
    
    If the model produces an error, return an empty string
    """
    
    prompt = create_prompt(question, df, max_prompt_tokens)
    
    try:
        response = openai.Completion.create(
            model=COMPLETION_MODEL_NAME,
            prompt=prompt,
            max_tokens=max_answer_tokens
        )
        return response["choices"][0]["text"].strip()
    except Exception as e:
        print(e)
        return ""

## Custom Performance Demonstration

TODO: In the cells below, demonstrate the performance of your custom query using at least 2 questions. For each question, show the answer from a basic `Completion` model query as well as the answer from your custom query.

### Question 1

In [32]:
# initial answer without context
popular_fashion_prompt = """
Question: "What was the most popular fashion trends in 2023?"
Answer:
"""
initial_popular_fashion_answer = openai.Completion.create(
    model="gpt-3.5-turbo-instruct",
    prompt=popular_fashion_prompt,
    max_tokens=150
)["choices"][0]["text"].strip()


# answer with context
custom_popular_fashion_answer = answer_question("What was the most popular fashion trends in 2023?", df)

print(f"""
What was the most popular fashion trends in 2023?

Original Answer: {initial_popular_fashion_answer}

Custom Answer:   {custom_popular_fashion_answer}
""")

What was the most popular fashion trends in 2023?

Original Answer: It is impossible to predict the fashion trends in 2023 as they are constantly changing and influenced by various factors. However, some possible trends that may gain popularity in 2023 could include sustainable and eco-friendly fashion, oversized and relaxed silhouettes, pastel colors, and old-school 90s fashion making a comeback.

Custom Answer:   Some of the most popular fashion trends in 2023 are sheer clothing, red, cobalt blue, cargo pants, pinstripe tailoring, indie sleaze, perfectly cut trousers, shine for daytime, and more mesh.

As we can see clearly from the above example, the model wasn't able to provide a precise answer without context in the prompt, comparing it with the prompt provided. This demonestrates the capabilities of providing contex to the model when it wasn't trained on specific datasets.

### Question 2

In [34]:
# initial answer without context
popular_fashion_prompt = """
Question: "List down the top 5 fashion trends in 2023."
Answer:
"""
initial_popular_fashion_answer = openai.Completion.create(
    model="gpt-3.5-turbo-instruct",
    prompt=popular_fashion_prompt,
    max_tokens=150
)["choices"][0]["text"].strip()


# answer with context
custom_popular_fashion_answer = answer_question("List down the top 5 fashion trends in 2023.", df)

print(f"""
List down the top 5 fashion trends in 2023.

Original Answer: 
{initial_popular_fashion_answer}

Custom Answer:   
{custom_popular_fashion_answer}

""")

List down the top 5 fashion trends in 2023.

Original Answer:
1. Sustainability and ethical fashion - With rising awareness about the environmental impact of the fashion industry, there is a growing demand for sustainable and ethical fashion options. In 2023, expect to see more brands incorporating eco-friendly materials, ethical production practices, and circular fashion processes.

2. Bold, statement pieces - Bold and eye-catching pieces will dominate fashion trends in 2023. From oversized silhouettes to vibrant colors and prints, expect to see a lot of statement pieces that exude confidence and individuality.

3. Nostalgic fashion - Nostalgic fashion trends from the '90s and early 2000s will continue to make a comeback in 2023. Look out for chunky jewelry, tie-dye prints

Custom Answer:
1. Sheer clothing
2. Shine for daytime
3. Maxi skirts
4. Cargo pants
5. Cobalt blue

From the answers above, we can see that the model wasn't able to list down 5 answers as requested, and seemed to provide long text that is not as precise as the context aware model.